"""Pydantic models for video analysis pipeline."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class VideoFrame(BaseModel):
    """A single extracted video frame with metadata."""

    frame_index: int
    timestamp_ms: float  # Position in video (ms)
    timestamp_wall: Optional[datetime] = None  # Wall-clock if derivable
    file_path: str  # Path to extracted frame image
    width: int
    height: int
    # Detected UI elements / text via vision model
    detected_elements: list[str] = Field(default_factory=list)
    # Free-form caption generated by vision model
    caption: Optional[str] = None
    # Embedding vector for similarity search (not serialised by default)
    embedding: Optional[list[float]] = Field(default=None, exclude=True)


class VideoSegment(BaseModel):
    """A meaningful temporal segment of the recording."""

    segment_id: str
    start_ms: float
    end_ms: float
    label: str  # e.g. "parameter-tampering", "auth-bypass-attempt"
    description: str
    frames: list[VideoFrame] = Field(default_factory=list)
    # Key-frames chosen as representative of this segment
    key_frames: list[VideoFrame] = Field(default_factory=list)
    # Actions detected within segment
    detected_actions: list[str] = Field(default_factory=list)


class TemporalEvent(BaseModel):
    """An atomic action/event anchored to a video timestamp."""

    event_id: str
    timestamp_ms: float
    event_type: str  # "click", "input", "request", "response", "navigation"
    description: str
    # Associated frame
    frame: Optional[VideoFrame] = None
    # Associated Burp HTTP item IDs (populated during synchronisation)
    burp_item_ids: list[str] = Field(default_factory=list)
    # Structured payload (e.g. modified parameter name/value)
    payload: Optional[dict[str, Any]] = None


class VideoAnalysis(BaseModel):
    """Complete analysis result for a single video recording."""

    video_path: str
    video_duration_ms: float
    fps: float
    total_frames: int
    analysed_at: datetime = Field(default_factory=datetime.utcnow)

    frames: list[VideoFrame] = Field(default_factory=list)
    segments: list[VideoSegment] = Field(default_factory=list)
    events: list[TemporalEvent] = Field(default_factory=list)

    # High-level narrative produced by vision model
    overall_narrative: Optional[str] = None
    # Wall-clock start time of recording (for cross-referencing Burp)
    recording_start_wall: Optional[datetime] = None
